### ISSUE TITLE
Loading external images

### ISSUE THREAD

**Issue by simplenotezy** [regenrek/nuxt-lazyimage#3]
I am building a nuxt app that primarily load images from an external service. How does this work together with this plugin? Where will the compressed images be stored? What about CDN for the images?

Thanks in advance.

**Comment by regenrek** [comment]
Hi sorry for my late reply.

It depends on what CMS or Asset Provider you're using. We're using a slightly different component if we working with cms sites like sanity or storyblok.

**Comment by simplenotezy** [comment]
I see. Which component exactly?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by regenrek** [comment]
Hi which cms you are using?

**Comment by J05HI** [comment]
Hello @regenrek & @simplenotezy 
I'm also interested in the slightly modified component.
We're using storyblock and would like to download the images on [export](https://github.com/nuxt/nuxt.js/pull/6159). After that we would like to let the downloaded images be processed and rendered in your lazyload component.

**Comment by regenrek** [comment]
Wouldn't it better to use the storybloks image api directly instead of download them and process them via nuxt generate? https://www.storyblok.com/docs/Guides/how-to-resize-images

**Comment by J05HI** [comment]
@regenrek 
Yeah I would like to be independent for the live version. I'll upload them to a CDN myself.
Do you know how to do download them and replace the URL with the local one?

**Comment by regenrek** [comment]
I don't have a ready to go solution but maybe you can find something here:

https://github.com/bejamas/gatsby-storyblok-image
https://github.com/bejamas/gatsby-storyblok-image/pull/7/commits/778b89e91958b062a2d9cccc5cdbd94e5d0f2bdf

**Comment by J05HI** [comment]
@regenrek 
Great! Thank you very much!

**Comment by studiolathe** [comment]
> Hi sorry for my late reply.
> 
> It depends on what CMS or Asset Provider you're using. We're using a slightly different component if we working with cms sites like sanity or storyblok.

Hi there, I am currently looking to implement with Nuxt + Storyblok, do you by any chance have an example of this setup?

Thanks in advance!

**Comment by regenrek** [comment]
Hi @studiolathe 

for storyblok we're using something like this: https://gist.github.com/regenrek/f053917485463bbc99632c13ed9ca9b1
