### ISSUE TITLE
LQIP not working

### ISSUE THREAD

**Issue by J05HI** [regenrek/nuxt-lazyimage#7]
Hello @regenrek 
if I add :use-lqip="true" to your Codesandbox example I'm getting the following error:
![image](https://user-images.githubusercontent.com/16399787/81788210-78f4be00-9502-11ea-968b-4b104df46b8a.png)

**Comment by regenrek** [comment]
Hi @J05HI 

Well yes, I removed LQIP in a later version which I have never released. It seems that the lqip loader has issues I'm not sure what exactly the issue.

**Comment by J05HI** [comment]
@regenrek 
Oh okay, thanks! I'll figure it out by myself 😉
